"""empty message

Revision ID: bcf9dee81532
Revises: dd510d2388fe
Create Date: 2020-12-15 18:06:43.300779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf9dee81532'
down_revision = 'dd510d2388fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('reservation', sa.Column('is_listed', sa.Boolean(), nullable=True))
    op.add_column('reservation', sa.Column('name', sa.String(), nullable=False))
    op.add_column('reservation', sa.Column('room', sa.String(), nullable=False))
    op.add_column('reservation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('reservation_roomreservation_id_fkey', 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    op.drop_column('reservation', 'listed')
    op.drop_column('reservation', 'roomreservation_id')
    op.drop_column('reservation', 'room_id')
    op.alter_column('room', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('room', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_unique_constraint(None, 'room', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='unique')
    op.alter_column('room', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('room', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('reservation', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservation', sa.Column('roomreservation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('listed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key('reservation_roomreservation_id_fkey', 'reservation', 'room', ['roomreservation_id'], ['id'])
    op.drop_column('reservation', 'user_id')
    op.drop_column('reservation', 'room')
    op.drop_column('reservation', 'name')
    op.drop_column('reservation', 'is_listed')
    op.drop_column('reservation', 'date')
    # ### end Alembic commands ###
