"""empty message

Revision ID: cbd90098aba1
Revises: 67e56ee41abf
Create Date: 2020-12-13 18:57:01.970471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd90098aba1'
down_revision = '67e56ee41abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('room_reserver_id_fkey', 'room', type_='foreignkey')
    op.drop_column('room', 'reserver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('reserver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('room_reserver_id_fkey', 'room', 'user', ['reserver_id'], ['id'])
    op.drop_column('room', 'updated_at')
    # ### end Alembic commands ###
