"""empty message

Revision ID: dd510d2388fe
Revises: bdf466fbafc4
Create Date: 2020-12-14 17:25:58.086484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd510d2388fe'
down_revision = 'bdf466fbafc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('is_listed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'is_listed')
    # ### end Alembic commands ###
